### PR TITLE
Power Enum Incompatible with Rails 7x

### PR DESCRIPTION
**Pull request by joel**
I'm puzzled by the claim made about the fact that:

> "PowerEnum 4. X (this version) supports Rails 6. X and Rails 7.0

I try to run the test suite in the matrix Rails x Ruby to check this out.

I removed the generated dummy app and created a new one with the corresponding Rails version.

First of all, Rails 6x work only if we enforce to use of the Rails autoload and not Zeitweik. This makes sense as the power enum uses the [Rails autoloading mechanism internally](https://github.com/albertosaurus/power_enum_2/blob/master/lib/active_record/virtual_enumerations.rb#L78).

As [Rails 7 does not support Rails autoloading](https://github.com/rails/rails/blob/v7.0.4.2/activesupport/lib/active_support/dependencies.rb), how would power still work?

On top of that, it seems that create_enum is broken in 7x too.

### CODE REVIEW

**Comment by albertosaurus** [comment]
Is this a work in progress, or...? It's not marked as such, but it completely breaks the test suite.

As things stand, all specs in master pass with Rails 7.0.4.1.

**Comment by joel** [comment]
Hi Albert, this is not a work in progress. The test passes all the following matrices:

Screenshot 2023-02-03 at 10 42 48 AM

In that PR, the test suite is run by GitHub Actions, and the tests are run per matrix and in a dummy app created with the correct version of Rails. See the following commands:

 1. bundle exec bin/setup
 2. bundle exec bin/dummy_setup ensure_classic_autoloading
 3. bundle exec rake

You can probably run them if turning on GA on your repository.

It sounds impossible to have power enum code working with Rails 7 as it uses the Rails autoload code:

Screenshot 2023-02-03 at 10 50 51 AM

That code has been completely removed in Rails 7.

You mentioned that the test suite doesn’t pass anymore. Where can that test suite be found? Is that only on a dev environment on a specific machine? As the dummy has been removed, it makes sense, though. The dummy app needs to be regenerated to suit the Rails version.

**Comment by albertosaurus** [comment]
@joel At the bottom of the README: https://github.com/albertosaurus/power_enum_2#how-to-run-tests

Which I just realized will only pass if you already have an existing test database, because `create_enum` conflicts with `create_enum` introduced in the Rails 7 Postgres adapter. I'm going to need to rethink my options.

**Comment by albertosaurus** [comment]
OK. Current master is now "fixed", but the fundamental incompatibility doesn't go away.

**Comment by albertosaurus** [comment]
@joel Are you currently using this with Rails 7?

**Comment by joel** [comment]
@albertosaurus, we are preparing the upgrade and identifying what would block us. Power Enum is a blocker for us.

**Comment by joel** [comment]
@albertosaurus, to give a final update here, we moved to Rails 7, removing the VirtualEnumerations part of the code, and we finally decided to remove all the code depending on PowerEnum as we weren’t using that many of the features.

**Pull request closed without merging**
